name: Class Reminder

on:
  schedule:
    - cron: '* * * * *'   # every 1 minute
  workflow_dispatch:        # allow manual trigger

jobs:
  send-reminders:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests pycryptodome

      - name: Run reminder script
        env:
          CRON_URL: ${{ secrets.CRON_URL }}
        run: python reminder.py
